const permissions = {
    'ADMINISTRATOR': 'Administrator',
    'CREATE_INSTANT_INVITE': 'Create Instant Invite',
    'KICK_MEMBERS': 'Kick Members',
    'BAN_MEMBERS': 'Ban Members',
    'MANAGE_CHANNELS': 'Manage Channels',
    'MANAGE_GUILD': 'Manage Server',
    'ADD_REACTIONS': 'Add Reactions',
    'VIEW_AUDIT_LOG': 'View Audit Log',
    'PRIORITY_SPEAKER': 'Priority Speaker',
    'VIEW_CHANNEL': 'View Channels',
    'SEND_MESSAGES': 'Send Messages',
    'SEND_TTS_MESSAGES': 'Send TTS Messages',
    'MANAGE_MESSAGES': 'Manage Messages',
    'EMBED_LINKS': 'Embed Links',
    'ATTACH_FILES': 'Attach Files',
    'READ_MESSAGE_HISTORY': 'Read Message History',
    'MENTION_EVERYONE': 'Mention Everyone',
    'USE_EXTERNAL_EMOJIS': 'Use External Emojis',
    'CONNECT': 'Connect',
    'SPEAK': 'Speak',
    'MUTE_MEMBERS': 'Mute Members',
    'DEAFEN_MEMBERS': 'Deafen Members',
    'MOVE_MEMBERS': 'Use (Move) Members',
    'USE_VAD': 'Use Voice Activity',
    'CHANGE_NICKNAME': 'Change Nickname',
    'MANAGE_NICKNAMES': 'Manage Nicknames',
    'MANAGE_ROLES': 'Manage Roles',
    'MANAGE_WEBHOOKS': 'Manage Webhooks',
    'MANAGE_EMOJIS': 'Mange Emojis',

};

module.exports = permissions;